// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System;

namespace Totekoya.Tables
{
   public sealed partial class TestMasterMemoryTable : TableBase<TestMasterMemory>, ITableUniqueValidate
   {
        public Func<TestMasterMemory, int> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<TestMasterMemory, int> primaryIndexSelector;

        readonly TestMasterMemory[] secondaryIndex0;
        readonly Func<TestMasterMemory, int> secondaryIndex0Selector;
        readonly TestMasterMemory[] secondaryIndex1;
        readonly Func<TestMasterMemory, (Gender Gender, int Age)> secondaryIndex1Selector;
        readonly TestMasterMemory[] secondaryIndex2;
        readonly Func<TestMasterMemory, Gender> secondaryIndex2Selector;

        public TestMasterMemoryTable(TestMasterMemory[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.PersonId;
            this.secondaryIndex0Selector = x => x.Age;
            this.secondaryIndex0 = CloneAndSortBy(this.secondaryIndex0Selector, System.Collections.Generic.Comparer<int>.Default);
            this.secondaryIndex1Selector = x => (x.Gender, x.Age);
            this.secondaryIndex1 = CloneAndSortBy(this.secondaryIndex1Selector, System.Collections.Generic.Comparer<(Gender Gender, int Age)>.Default);
            this.secondaryIndex2Selector = x => x.Gender;
            this.secondaryIndex2 = CloneAndSortBy(this.secondaryIndex2Selector, System.Collections.Generic.Comparer<Gender>.Default);
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();

        public RangeView<TestMasterMemory> SortByAge => new RangeView<TestMasterMemory>(secondaryIndex0, 0, secondaryIndex0.Length - 1, true);
        public RangeView<TestMasterMemory> SortByGenderAndAge => new RangeView<TestMasterMemory>(secondaryIndex1, 0, secondaryIndex1.Length - 1, true);
        public RangeView<TestMasterMemory> SortByGender => new RangeView<TestMasterMemory>(secondaryIndex2, 0, secondaryIndex2.Length - 1, true);

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public TestMasterMemory FindByPersonId(int key)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].PersonId;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { return data[mid]; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            return ThrowKeyNotFound(key);
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public bool TryFindByPersonId(int key, out TestMasterMemory result)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].PersonId;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { result = data[mid]; return true; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            result = default;
            return false;
        }

        public TestMasterMemory FindClosestByPersonId(int key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, key, selectLower);
        }

        public RangeView<TestMasterMemory> FindRangeByPersonId(int min, int max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, min, max, ascendant);
        }

        public RangeView<TestMasterMemory> FindByAge(int key)
        {
            return FindManyCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<int>.Default, key);
        }

        public RangeView<TestMasterMemory> FindClosestByAge(int key, bool selectLower = true)
        {
            return FindManyClosestCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<int>.Default, key, selectLower);
        }

        public RangeView<TestMasterMemory> FindRangeByAge(int min, int max, bool ascendant = true)
        {
            return FindManyRangeCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<int>.Default, min, max, ascendant);
        }

        public RangeView<TestMasterMemory> FindByGenderAndAge((Gender Gender, int Age) key)
        {
            return FindManyCore(secondaryIndex1, secondaryIndex1Selector, System.Collections.Generic.Comparer<(Gender Gender, int Age)>.Default, key);
        }

        public RangeView<TestMasterMemory> FindClosestByGenderAndAge((Gender Gender, int Age) key, bool selectLower = true)
        {
            return FindManyClosestCore(secondaryIndex1, secondaryIndex1Selector, System.Collections.Generic.Comparer<(Gender Gender, int Age)>.Default, key, selectLower);
        }

        public RangeView<TestMasterMemory> FindRangeByGenderAndAge((Gender Gender, int Age) min, (Gender Gender, int Age) max, bool ascendant = true)
        {
            return FindManyRangeCore(secondaryIndex1, secondaryIndex1Selector, System.Collections.Generic.Comparer<(Gender Gender, int Age)>.Default, min, max, ascendant);
        }

        public RangeView<TestMasterMemory> FindByGender(Gender key)
        {
            return FindManyCore(secondaryIndex2, secondaryIndex2Selector, System.Collections.Generic.Comparer<Gender>.Default, key);
        }

        public RangeView<TestMasterMemory> FindClosestByGender(Gender key, bool selectLower = true)
        {
            return FindManyClosestCore(secondaryIndex2, secondaryIndex2Selector, System.Collections.Generic.Comparer<Gender>.Default, key, selectLower);
        }

        public RangeView<TestMasterMemory> FindRangeByGender(Gender min, Gender max, bool ascendant = true)
        {
            return FindManyRangeCore(secondaryIndex2, secondaryIndex2Selector, System.Collections.Generic.Comparer<Gender>.Default, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
            ValidateUniqueCore(data, primaryIndexSelector, "PersonId", resultSet);       
        }

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(TestMasterMemory), typeof(TestMasterMemoryTable), "person",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(TestMasterMemory).GetProperty("PersonId")),
                    new MasterMemory.Meta.MetaProperty(typeof(TestMasterMemory).GetProperty("Age")),
                    new MasterMemory.Meta.MetaProperty(typeof(TestMasterMemory).GetProperty("Gender")),
                    new MasterMemory.Meta.MetaProperty(typeof(TestMasterMemory).GetProperty("Name")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(TestMasterMemory).GetProperty("PersonId"),
                    }, true, true, System.Collections.Generic.Comparer<int>.Default),
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(TestMasterMemory).GetProperty("Age"),
                    }, false, false, System.Collections.Generic.Comparer<int>.Default),
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(TestMasterMemory).GetProperty("Gender"),
                        typeof(TestMasterMemory).GetProperty("Age"),
                    }, false, false, System.Collections.Generic.Comparer<(Gender Gender, int Age)>.Default),
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(TestMasterMemory).GetProperty("Gender"),
                    }, false, false, System.Collections.Generic.Comparer<Gender>.Default),
                });
        }

    }
}